/* Autogenerated, do not edit */
#ifndef NSB_VERSION_H__
#define NSB_VERSION_H__
#define NSB_VERSION "1.0"
#define NSB_VERSION_MAJOR  1
#define NSB_VERSION_MINOR  0
#define NSB_GITID "f01768f"
#endif /* NSB_VERSION_H__ */
